version: "3.4"

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:${API_HTTPS_PORT};http://+:${API_HTTP_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
      - ${API_HTTPS_PORT}:${API_HTTPS_PORT}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}\.aspnet\https:/https/
      - ./containers/logs:/logs
